# Generated by Django 3.0.5 on 2020-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_first_name', models.CharField(max_length=12)),
                ('candidate_middle_name', models.CharField(max_length=12)),
                ('candidate_last_name', models.CharField(max_length=12)),
                ('candidate_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_first_name', models.CharField(max_length=12)),
                ('voter_last_name', models.CharField(max_length=12)),
                ('voter_id', models.IntegerField(default=0)),
                ('voter_choice', models.CharField(max_length=30)),
                ('vote_submit_time', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
    ]
