# Generated by Django 3.0.5 on 2020-04-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='vote_submit_time',
        ),
    ]
